import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";

import { createTranslator } from "@game/i18n";
import type {
  TacticalShapeAuditReport,
  TacticalShapeInvariantResult,
} from "@game/simulation-tools";

import {
  createTacticalShapeReport,
  DEFAULT_TACTICAL_SHAPE_FORMATION_PAIRED_SEEDS,
  DEFAULT_TACTICAL_SHAPE_PAIRED_SEEDS,
  DEFAULT_TACTICAL_SHAPE_SCENARIO_PAIRED_SEEDS,
  DEFAULT_TACTICAL_SHAPE_SEED_PREFIX,
  DEFAULT_TACTICAL_SHAPE_WORLD_SEED,
  type CreateTacticalShapeReportInput,
  type TacticalShapeReportBundle,
} from "./tactical-shape-report-data.ts";

/**
 * Everything the command reaches outside itself.
 *
 * `createReport` is part of the seam because generating a world and running the
 * full baseline costs minutes; command tests supply a small bundle instead and
 * exercise argument parsing, rendering, and exit codes on their own.
 */
export interface TacticalShapeReportCommandDependencies {
  /** Writes normal command output. */
  readonly stdout: (line: string) => void;
  /** Writes command errors. */
  readonly stderr: (line: string) => void;
  /** Writes the rendered report to a path, creating parent directories. */
  readonly writeReport: (path: string, contents: string) => Promise<void>;
  /** Produces the audit bundle for the parsed arguments. */
  readonly createReport: (input: CreateTacticalShapeReportInput) => TacticalShapeReportBundle;
}

/**
 * Runs the deterministic tactical-shape baseline and renders it as Markdown.
 *
 * The command is a reporting path only: it changes no gameplay and its exit
 * code reflects whether every frozen invariant that could be evaluated passed.
 *
 * @example
 * await runTacticalShapeReportCommand(["--report-output=docs/audits/report.md"]);
 */
export async function runTacticalShapeReportCommand(
  args: readonly string[],
  dependencies: TacticalShapeReportCommandDependencies = defaultDependencies(),
): Promise<number> {
  const parsed = parseArgs(args);
  const text = createTranslator("en");

  if (!parsed.ok) {
    dependencies.stderr(parsed.message);
    dependencies.stderr(text("tacticalShape.usage"));
    return 1;
  }

  const bundle = dependencies.createReport({
    worldSeed: parsed.worldSeed,
    seedPrefix: parsed.seedPrefix,
    pairedSeedCount: parsed.pairedSeedCount,
    scenarioPairedSeedCount: parsed.scenarioPairedSeedCount,
    formationPairedSeedCount: parsed.formationPairedSeedCount,
  });
  const rendered = formatTacticalShapeReport(bundle);

  if (parsed.reportOutput === undefined) {
    dependencies.stdout(rendered);
  } else {
    await dependencies.writeReport(parsed.reportOutput, rendered);
    dependencies.stdout(text("tacticalShape.reportWritten", { path: parsed.reportOutput }));
  }

  return countFailedInvariants(bundle.report) === 0 ? 0 : 1;
}

/** Renders one audit bundle as the frozen Markdown baseline document. */
export function formatTacticalShapeReport(bundle: TacticalShapeReportBundle): string {
  const { report, measurement } = bundle;

  return [
    "# Phase 81 Tactical Shape Baseline",
    "",
    "Generated by `pnpm cli tactical-shape-report`. Every number below comes from",
    "the production `deriveTeamStrength` and `simulateMatch` paths; this command",
    "changes no gameplay behaviour.",
    "",
    ...metadataSection(bundle),
    "",
    ...bandsSection(bundle),
    "",
    ...strengthSection(report),
    "",
    ...equivalenceSection(report),
    "",
    ...versusReferenceSection(report),
    "",
    ...tacticSection(report),
    "",
    ...formationSection(report),
    "",
    ...formationDominanceSection(report),
    ...selectionConcentrationSection(report),
    "",
    ...qualitySection(report),
    "",
    ...invariantSection(report),
    "",
    ...dominanceSection(report),
    "",
    `Measured from world seed \`${measurement.worldSeed}\`.`,
    "",
  ].join("\n");
}

function metadataSection(bundle: TacticalShapeReportBundle): readonly string[] {
  const { report } = bundle;

  return [
    "## Run Identity",
    "",
    "| Field | Value |",
    "| --- | --- |",
    `| Contract version | \`${report.contractVersion}\` |`,
    `| Seed prefix | \`${report.seedPrefix}\` |`,
    `| Seed pairs per dominance cell | ${report.pairedSeedCount} |`,
    `| Seed pairs per scenario | ${report.scenarioPairedSeedCount} |`,
    `| Seed pairs per formation-matrix cell | ${report.formationPairedSeedCount} |`,
    `| Formation-matrix row-mean noise floor | ${report.formationDominance.matrixNoiseFloor} |`,
    `| Matches behind the dominance matrix | ${report.dominance.matches} |`,
    `| Versus-reference noise floor | ${report.versusReferenceNoiseFloor} |`,
    `| Structured hash | \`${report.structuredHash}\` |`,
  ];
}

function bandsSection(bundle: TacticalShapeReportBundle): readonly string[] {
  const rows = bundle.report.bands.map((band) => {
    const provenance = bundle.measurement.provenance[band.bandKey];
    const source =
      provenance === undefined
        ? "-"
        : `${provenance.clubId} (rank ${provenance.divisionRank}/${provenance.divisionSize})`;
    return `| \`${band.bandKey}\` | ${band.goalkeeper} | ${band.defense} | ${band.midfield} | ${band.attack} | ${source} |`;
  });

  return [
    "## Measured Quality Bands",
    "",
    "Department scores measured from the generated first-choice eleven of a real",
    "club, through the production team-strength path. The `reference` band is the",
    "median first-division club flattened to one uniform value, so that every",
    "structural comparison has a single unambiguous quality number.",
    "",
    "These bands hold for a **single-country population**. With five countries,",
    "`first division` and `third division` stop denoting one quality scale and",
    "every band below must be re-derived rather than carried over.",
    "",
    "| Band | GK | Defense | Midfield | Attack | Measured from |",
    "| --- | --- | --- | --- | --- | --- |",
    ...rows,
  ];
}

function strengthSection(report: TacticalShapeAuditReport): readonly string[] {
  const grouped = new Map<string, string[]>();
  for (const row of report.strengthRows) {
    const keys = grouped.get(row.fingerprint) ?? [];
    keys.push(row.compositionKey);
    grouped.set(row.fingerprint, keys);
  }

  const rows = [...grouped.entries()].map(([fingerprint, keys]) => {
    const strength = report.strengthRows.find((row) => row.fingerprint === fingerprint)?.strength;
    return (
      `| ${keys.length} | ${score(strength?.goalkeeper)} | ${score(strength?.defense)} `
      + `| ${score(strength?.midfield)} | ${score(strength?.attack)} | ${score(strength?.overall)} `
      + `| ${keys.slice(0, 5).join(", ")}${keys.length > 5 ? ", ..." : ""} |`
    );
  });

  return [
    "## Department Collapse",
    "",
    `The reachable population is ${report.strengthRows.length} department compositions, which the current`,
    `engine reduces to **${report.distinctStrengthCount} distinct team strengths**. Every composition that`,
    "populates all four departments produces byte-identical strength, because",
    "`deriveTeamStrength` averages inside a department and therefore cannot see how",
    "many slots are in it. The only structural signal the engine has today is",
    "whether a department is *empty*.",
    "",
    "| Compositions | GK | Defense | Midfield | Attack | Overall | Members |",
    "| --- | --- | --- | --- | --- | --- | --- |",
    ...rows,
    "",
    `Compositions reachable from one of the 23 named presets: ${report.strengthRows.filter((row) => row.reachableFromPreset).length}.`,
    "The rest are reachable only by moving players on the tactical board, which no",
    "validator prevents.",
  ];
}

function equivalenceSection(report: TacticalShapeAuditReport): readonly string[] {
  const rows = report.equivalences.map(
    (row) =>
      `| \`${row.firstCompositionKey}\` | \`${row.secondCompositionKey}\` | ${yesNo(row.strengthIdentical)} `
      + `| ${yesNo(row.resultsIdentical)} | ${row.matches} |`,
  );

  return [
    "## Shape Equivalence",
    "",
    "Both compositions run on the same seeds and the same fixture identities, so a",
    "difference in results can only come from the shape.",
    "",
    "| Shape | Shape | Identical strength | Identical results | Matches |",
    "| --- | --- | --- | --- | --- |",
    ...rows,
  ];
}

function versusReferenceSection(report: TacticalShapeAuditReport): readonly string[] {
  const ordered = [...report.versusReference].sort((left, right) => right.winShare - left.winShare);
  const rows = ordered.map(
    (row) =>
      `| \`${row.compositionKey}\` | ${row.winShare} | ${row.possessionShare} | ${row.clampedTo} `
      + `| ${row.opportunities} | ${row.expectedGoals} | ${row.goals} | ${row.matches} |`,
  );

  return [
    "## Every Shape Against The Reference Shape",
    "",
    "Each reachable composition against a coherent `4-4-2` at equal quality. This is",
    "the manager's real decision, so it is measured at the higher scenario",
    "precision and is what the bounded-swing and asymmetry invariants read.",
    "",
    "| Shape | Win share | Possession | Clamp | Opportunities | xG | Goals | Matches |",
    "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ...rows,
  ];
}

function tacticSection(report: TacticalShapeAuditReport): readonly string[] {
  const matrix = report.tacticDominance;
  const rows = matrix.rows.map((row) => {
    const types = row.chanceTypes;
    return (
      `| \`${row.tacticKey}\` | ${row.meanWinShareAgainstField} | ${row.minimumWinShareAgainstField} `
      + `| ${row.winShare} | ${row.possessionShare} | ${row.opportunities} | ${row.opportunitiesConceded} `
      + `| ${row.expectedGoals} | ${types.open_play} | ${types.counter} | ${types.cross} | ${row.matches} |`
    );
  });

  const header = `| vs | ${matrix.tacticKeys.map((key) => `\`${key}\``).join(" | ")} |`;
  const grid = matrix.rows.map(
    (row, index) =>
      `| \`${row.tacticKey}\` | ${(matrix.winShare[index] as readonly number[]).join(" | ")} |`,
  );

  return [
    "## Tactic Profiles At The Reference Shape",
    "",
    "Each profile moves one knob to its extreme, and every profile plays every",
    "other one on the same shape at the same quality, so whatever moves belongs to",
    "the tactic. `Against field` excludes the mirror match, which is `0.5` by",
    "construction, and it is what the `no_dominant_tactic` gate reads.",
    "",
    "`Conceded` is what the opponents produced. It is the half of a tactic that a",
    "win share hides: a defensive setting is supposed to buy fewer chances against",
    "it, not merely fewer of its own.",
    "",
    "| Tactic | Against field | Worst matchup | Against neutral | Possession | Created | Conceded | xG | Open play | Counter | Cross | Matches |",
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ...rows,
    "",
    "### Tactic Versus Tactic",
    "",
    "Row against column. The diagonal is `0.5` by construction and is not played.",
    "",
    header,
    `| --- | ${matrix.tacticKeys.map(() => "---").join(" | ")} |`,
    ...grid,
  ];
}

/**
 * Reports what fielding a differently-distributed eleven is worth.
 *
 * The one manager decision every other table here is blind to. All of them are
 * measured on clones - eleven identical players, which is what makes department
 * composition the only variable - so nothing else in this report can see which
 * players a manager picks. Both sides below field the same composition, the same
 * tactics and the same attack department strength; only the distribution of that
 * quality differs.
 */
function selectionConcentrationSection(report: TacticalShapeAuditReport): readonly string[] {
  const row = report.selectionConcentration;
  const edge = Math.round(Math.abs(row.concentratedWinShare - 0.5) * 10_000) / 10_000;
  const resolved = edge > row.noiseFloor;

  return [
    "## What A Standout Player Is Worth, At Equal Squad Quality",
    "",
    "Every other table in this report is measured on identical players, which is",
    "correct for isolating shape and blind to team selection. Here one attacker is",
    `lifted by \`${row.attackConcentration}\` ability points and his fellow attackers pay for it`,
    "exactly, so both sides carry the same attack department and any difference is",
    "about who takes the chances rather than about who has the better squad.",
    "",
    "| Measurement | Value |",
    "| --- | --- |",
    `| Concentrated side win share | ${row.concentratedWinShare} |`,
    `| Distance from an even contest | ${edge} |`,
    `| Noise floor at this sample | ${row.noiseFloor} |`,
    `| Resolved above the floor | ${resolved ? "yes" : "no"} |`,
    `| Attack strength, flat side | ${row.flatAttackStrength} |`,
    `| Attack strength, concentrated side | ${row.concentratedAttackStrength} |`,
    `| Matches | ${row.matches} |`,
    "",
    "The two attack strengths must be equal. If they ever differ, this row has",
    "stopped measuring distribution and become a squad-quality comparison.",
    "",
  ];
}

function formationSection(report: TacticalShapeAuditReport): readonly string[] {
  const rows = report.formations.map((row) => {
    const types = row.chanceTypes;
    const total = types.open_play + types.counter + types.cross;
    const crossShare = total === 0 ? 0 : Math.round((types.cross / total) * 10_000) / 10_000;
    return (
      `| \`${row.formationKey}\` | ${row.winShare} | ${row.possessionShare} | ${row.opportunities} `
      + `| ${row.expectedGoals} | ${row.goals} | ${types.open_play} | ${types.counter} | ${types.cross} `
      + `| ${crossShare} | ${row.matches} |`
    );
  });
  const slider = report.formationVersusSlider;

  return [
    "## Formations Against The Reference Formation",
    "",
    "The department population above cannot answer this. It builds every side from",
    "centre backs, central midfielders and strikers with no flank, so `4-4-2` and",
    "`4-3-2-1` differ there only by how many players sit in each department and not",
    "at all by where they stand. This table is the decision the tactical board",
    "actually exposes, and it is the only population in which a wing exists.",
    "",
    "| Formation | Win share | Possession | Opportunities | xG | Goals | Open play | Counter | Cross | Cross share | Matches |",
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ...rows,
    "",
    "### What The Formation Decides Against What One Slider Decides",
    "",
    "Both numbers are the share of chances that came down a flank, so they compare",
    "directly. Below `1` means dragging one dial moves the game more than choosing",
    "where eleven players stand.",
    "",
    "| Measurement | Value |",
    "| --- | --- |",
    `| Reference formation cross share | ${slider.referenceCrossShare} |`,
    `| Widest formation | ${slider.widestFormationCrossShare} |`,
    `| Narrowest formation | ${slider.narrowestFormationCrossShare} |`,
    `| \`width\` slider at its floor | ${slider.sliderFloorCrossShare} |`,
    `| \`width\` slider at its cap | ${slider.sliderCapCrossShare} |`,
    `| Formation span as a share of slider span | ${slider.formationShareOfSliderSpan} |`,
  ];
}

/**
 * Reports whether choosing a formation against the one you face is worth
 * anything.
 *
 * The table above it is a *column*: every measured formation against `4-4-2`.
 * It can say whether a shape is better than the reference and it structurally
 * cannot say whether one shape answers another, which is the entire question.
 * This is the matrix, over the whole catalog a manager picks from.
 */
function formationDominanceSection(report: TacticalShapeAuditReport): readonly string[] {
  const matrix = report.formationDominance;
  const aggregate = [...matrix.rows]
    .sort((left, right) => right.meanWinShareAgainstField - left.meanWinShareAgainstField)
    .map(
      (row) =>
        `| \`${row.formationKey}\` | ${row.meanWinShareAgainstField} | ${row.minimumWinShareAgainstField} `
        + `| \`${row.worstAgainstKey}\` | ${row.matches} |`,
    );
  const counterMoves = matrix.counterMoves.map(
    (row) =>
      `| \`${row.opponentKey}\` | \`${row.responseKey}\` | ${row.winShare} | ${row.gain} | ${row.matches} |`,
  );
  const grid = matrix.winShare.map((row, index) =>
    [matrix.formationKeys[index] ?? "?", ...row.map((value) => value.toFixed(3))].join("\t"),
  );

  return [
    "## Formation Against Formation",
    "",
    "Every curated formation against every other one at equal quality on neutral",
    "tactics. `Against field` excludes the mirror match, which is `0.5` by",
    "construction, and it is what the `no_dominant_formation` gate reads: these are",
    "all shapes a manager legitimately picks, so the mean *is* the expected value of",
    "choosing one blind.",
    "",
    `Row means resolve to \`${matrix.matrixNoiseFloor}\`; one replayed counter-move cell resolves`,
    `to \`${matrix.counterMoveNoiseFloor}\`.`,
    "",
    "| Formation | Against field | Worst matchup | Held there by | Matches |",
    "| --- | --- | --- | --- | --- |",
    ...aggregate,
    "",
    "### What Answering The Opponent Was Worth",
    "",
    "The best response to each opponent is **chosen on the matrix above and replayed",
    "on its own seed stream**. A maximum taken over the same sample it was picked",
    "from is biased upward by about the noise floor of a 23-way maximum, which would",
    "manufacture a counter-move reward out of sampling alone.",
    "",
    "| Opponent | Best response | Win share | Gain | Matches |",
    "| --- | --- | --- | --- | --- |",
    ...counterMoves,
    "",
    "| Measurement | Value |",
    "| --- | --- |",
    `| Mean gain from countering | ${matrix.meanCounterMoveGain} |`,
    `| Worst opponent's gain | ${matrix.worstCounterMoveGain} |`,
    `| Distinct shapes used as an answer | ${matrix.distinctResponseCount} of ${matrix.formationKeys.length} |`,
    `| Resolvable above the floor | ${Math.abs(matrix.meanCounterMoveGain) > matrix.counterMoveNoiseFloor ? "yes" : "no"} |`,
    "",
    "A single distinct answer is not a counter-move. It is one formation that beats",
    "the field, and rewarding it would be the dominant strategy this phase forbids.",
    "",
    "### Formation Versus Formation",
    "",
    "Row against column. The diagonal is `0.5` by construction and is not played.",
    "",
    "```",
    [".", ...matrix.formationKeys].join("\t"),
    ...grid,
    "```",
  ];
}

function qualitySection(report: TacticalShapeAuditReport): readonly string[] {
  const rows = report.qualityVersusStructure.map((row) => {
    const series = row.series;
    return (
      `| \`${row.scenarioKey}\` | \`${row.first.compositionKey}\` / \`${row.first.bandKey}\` `
      + `| \`${row.second.compositionKey}\` / \`${row.second.bandKey}\` | ${series.firstWinShare} `
      + `| ${series.firstWins}/${series.draws}/${series.secondWins} | ${series.first.expectedGoals} `
      + `| ${series.second.expectedGoals} | ${series.matches} |`
    );
  });

  return [
    "## Quality Versus Structure",
    "",
    "`division_tier_edge` is the yardstick: what one division tier of squad quality",
    "is worth in win share at identical shape. The bounded-swing invariant compares",
    "the best structural gain against it.",
    "",
    "| Scenario | First | Second | First win share | W/D/L | First xG | Second xG | Matches |",
    "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ...rows,
  ];
}

function invariantSection(report: TacticalShapeAuditReport): readonly string[] {
  const rows = report.invariants.map(
    (invariant) =>
      `| \`${invariant.key}\` | ${statusLabel(invariant)} | ${invariant.observed ?? "-"} `
      + `| ${invariant.observations} | ${invariant.threshold} |`,
  );

  return [
    "## Frozen Invariants",
    "",
    "Thresholds were fixed before any behaviour change and are never re-derived",
    "from output. `not_evaluated` is never reported as a pass.",
    "",
    "| Invariant | Status | Observed | Observations | Frozen threshold |",
    "| --- | --- | --- | --- | --- |",
    ...rows,
    "",
    ...report.invariants.flatMap((invariant) => [`- \`${invariant.key}\`: ${invariant.detail}`]),
  ];
}

function dominanceSection(report: TacticalShapeAuditReport): readonly string[] {
  const keys = report.dominance.compositionKeys;
  const header = ["shape", ...keys].join("\t");
  const grid = report.dominance.winShare.map((row, index) =>
    [keys[index] ?? "?", ...row.map((value) => value.toFixed(3))].join("\t"),
  );
  const aggregate = report.dominance.rows.map(
    (row) => `| \`${row.compositionKey}\` | ${row.meanWinShare} | ${row.minimumWinShare} | ${row.matches} |`,
  );

  return [
    "## Dominance Matrix",
    "",
    `The full ${keys.length} x ${keys.length} paired-seed matrix over the reachable population. Row versus`,
    "column, read as the row's win share. Recorded in full rather than summarised,",
    "because dominance shows as a row and a summary hides it.",
    "",
    "| Shape | Mean vs field | Worst matchup | Matches |",
    "| --- | --- | --- | --- |",
    ...aggregate,
    "",
    "```tsv",
    header,
    ...grid,
    "```",
  ];
}

function statusLabel(invariant: TacticalShapeInvariantResult): string {
  switch (invariant.status) {
    case "pass":
      return "PASS";
    case "fail":
      return "FAIL";
    case "not_evaluated":
      return "not_evaluated";
  }
}

function countFailedInvariants(report: TacticalShapeAuditReport): number {
  return report.invariants.filter((invariant) => invariant.status === "fail").length;
}

function yesNo(value: boolean): string {
  return value ? "yes" : "no";
}

/**
 * Renders one department score for the report.
 *
 * Presentation rounds; the fingerprint that decides equivalence does not, so a
 * difference hidden by rounding here still shows as a distinct strength row.
 */
function score(value: number | undefined): string {
  return value === undefined ? "-" : value.toFixed(4);
}

interface ParsedArgsOk {
  readonly ok: true;
  readonly worldSeed: string;
  readonly seedPrefix: string;
  readonly pairedSeedCount: number;
  readonly scenarioPairedSeedCount: number;
  readonly formationPairedSeedCount: number;
  readonly reportOutput: string | undefined;
}

interface ParsedArgsInvalid {
  readonly ok: false;
  readonly message: string;
}

function parseArgs(args: readonly string[]): ParsedArgsInvalid | ParsedArgsOk {
  const text = createTranslator("en");
  let worldSeed = DEFAULT_TACTICAL_SHAPE_WORLD_SEED;
  let seedPrefix = DEFAULT_TACTICAL_SHAPE_SEED_PREFIX;
  let pairedSeedCount = DEFAULT_TACTICAL_SHAPE_PAIRED_SEEDS;
  let scenarioPairedSeedCount = DEFAULT_TACTICAL_SHAPE_SCENARIO_PAIRED_SEEDS;
  let formationPairedSeedCount = DEFAULT_TACTICAL_SHAPE_FORMATION_PAIRED_SEEDS;
  let reportOutput: string | undefined;

  for (const arg of args) {
    if (arg.startsWith("--world-seed=")) {
      worldSeed = arg.slice("--world-seed=".length);
      if (worldSeed.length === 0) {
        return { ok: false, message: text("tacticalShape.error.worldSeedRequired") };
      }
      continue;
    }

    if (arg.startsWith("--seed-prefix=")) {
      seedPrefix = arg.slice("--seed-prefix=".length);
      if (seedPrefix.length === 0) {
        return { ok: false, message: text("tenSeason.error.seedPrefixRequired") };
      }
      continue;
    }

    if (arg.startsWith("--paired-seeds=")) {
      const value = arg.slice("--paired-seeds=".length);
      pairedSeedCount = Number(value);
      if (!Number.isSafeInteger(pairedSeedCount) || pairedSeedCount <= 0) {
        return { ok: false, message: text("tacticalShape.error.pairedSeedsInvalid", { value }) };
      }
      continue;
    }

    if (arg.startsWith("--scenario-paired-seeds=")) {
      const value = arg.slice("--scenario-paired-seeds=".length);
      scenarioPairedSeedCount = Number(value);
      if (!Number.isSafeInteger(scenarioPairedSeedCount) || scenarioPairedSeedCount <= 0) {
        return { ok: false, message: text("tacticalShape.error.pairedSeedsInvalid", { value }) };
      }
      continue;
    }

    if (arg.startsWith("--formation-paired-seeds=")) {
      const value = arg.slice("--formation-paired-seeds=".length);
      formationPairedSeedCount = Number(value);
      if (!Number.isSafeInteger(formationPairedSeedCount) || formationPairedSeedCount <= 0) {
        return { ok: false, message: text("tacticalShape.error.pairedSeedsInvalid", { value }) };
      }
      continue;
    }

    if (arg.startsWith("--report-output=")) {
      reportOutput = arg.slice("--report-output=".length);
      if (reportOutput.length === 0) {
        return { ok: false, message: text("tacticalShape.error.reportOutputRequired") };
      }
      continue;
    }

    return { ok: false, message: text("cli.error.unknownArgument", { arg }) };
  }

  return {
    ok: true,
    worldSeed,
    seedPrefix,
    pairedSeedCount,
    scenarioPairedSeedCount,
    formationPairedSeedCount,
    reportOutput,
  };
}

function defaultDependencies(): TacticalShapeReportCommandDependencies {
  return {
    stdout: (line) => console.log(line),
    stderr: (line) => console.error(line),
    writeReport: async (path, contents) => {
      await mkdir(dirname(path), { recursive: true });
      await writeFile(path, contents, "utf8");
    },
    createReport: createTacticalShapeReport,
  };
}
