import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";

import { createTranslator } from "@game/i18n";
import type {
  TacticalShapeAuditReport,
  TacticalShapeInvariantResult,
} from "@game/simulation-tools";

import {
  createTacticalShapeReport,
  DEFAULT_TACTICAL_SHAPE_PAIRED_SEEDS,
  DEFAULT_TACTICAL_SHAPE_SCENARIO_PAIRED_SEEDS,
  DEFAULT_TACTICAL_SHAPE_SEED_PREFIX,
  DEFAULT_TACTICAL_SHAPE_WORLD_SEED,
  type CreateTacticalShapeReportInput,
  type TacticalShapeReportBundle,
} from "./tactical-shape-report-data.ts";

/**
 * Everything the command reaches outside itself.
 *
 * `createReport` is part of the seam because generating a world and running the
 * full baseline costs minutes; command tests supply a small bundle instead and
 * exercise argument parsing, rendering, and exit codes on their own.
 */
export interface TacticalShapeReportCommandDependencies {
  /** Writes normal command output. */
  readonly stdout: (line: string) => void;
  /** Writes command errors. */
  readonly stderr: (line: string) => void;
  /** Writes the rendered report to a path, creating parent directories. */
  readonly writeReport: (path: string, contents: string) => Promise<void>;
  /** Produces the audit bundle for the parsed arguments. */
  readonly createReport: (input: CreateTacticalShapeReportInput) => TacticalShapeReportBundle;
}

/**
 * Runs the deterministic tactical-shape baseline and renders it as Markdown.
 *
 * The command is a reporting path only: it changes no gameplay and its exit
 * code reflects whether every frozen invariant that could be evaluated passed.
 *
 * @example
 * await runTacticalShapeReportCommand(["--report-output=docs/audits/report.md"]);
 */
export async function runTacticalShapeReportCommand(
  args: readonly string[],
  dependencies: TacticalShapeReportCommandDependencies = defaultDependencies(),
): Promise<number> {
  const parsed = parseArgs(args);
  const text = createTranslator("en");

  if (!parsed.ok) {
    dependencies.stderr(parsed.message);
    dependencies.stderr(text("tacticalShape.usage"));
    return 1;
  }

  const bundle = dependencies.createReport({
    worldSeed: parsed.worldSeed,
    seedPrefix: parsed.seedPrefix,
    pairedSeedCount: parsed.pairedSeedCount,
    scenarioPairedSeedCount: parsed.scenarioPairedSeedCount,
  });
  const rendered = formatTacticalShapeReport(bundle);

  if (parsed.reportOutput === undefined) {
    dependencies.stdout(rendered);
  } else {
    await dependencies.writeReport(parsed.reportOutput, rendered);
    dependencies.stdout(text("tacticalShape.reportWritten", { path: parsed.reportOutput }));
  }

  return countFailedInvariants(bundle.report) === 0 ? 0 : 1;
}

/** Renders one audit bundle as the frozen Markdown baseline document. */
export function formatTacticalShapeReport(bundle: TacticalShapeReportBundle): string {
  const { report, measurement } = bundle;

  return [
    "# Phase 81 Tactical Shape Baseline",
    "",
    "Generated by `pnpm cli tactical-shape-report`. Every number below comes from",
    "the production `deriveTeamStrength` and `simulateMatch` paths; this command",
    "changes no gameplay behaviour.",
    "",
    ...metadataSection(bundle),
    "",
    ...bandsSection(bundle),
    "",
    ...strengthSection(report),
    "",
    ...equivalenceSection(report),
    "",
    ...versusReferenceSection(report),
    "",
    ...tacticSection(report),
    "",
    ...qualitySection(report),
    "",
    ...invariantSection(report),
    "",
    ...dominanceSection(report),
    "",
    `Measured from world seed \`${measurement.worldSeed}\`.`,
    "",
  ].join("\n");
}

function metadataSection(bundle: TacticalShapeReportBundle): readonly string[] {
  const { report } = bundle;

  return [
    "## Run Identity",
    "",
    "| Field | Value |",
    "| --- | --- |",
    `| Contract version | \`${report.contractVersion}\` |`,
    `| Seed prefix | \`${report.seedPrefix}\` |`,
    `| Seed pairs per dominance cell | ${report.pairedSeedCount} |`,
    `| Seed pairs per scenario | ${report.scenarioPairedSeedCount} |`,
    `| Matches behind the dominance matrix | ${report.dominance.matches} |`,
    `| Versus-reference noise floor | ${report.versusReferenceNoiseFloor} |`,
    `| Structured hash | \`${report.structuredHash}\` |`,
  ];
}

function bandsSection(bundle: TacticalShapeReportBundle): readonly string[] {
  const rows = bundle.report.bands.map((band) => {
    const provenance = bundle.measurement.provenance[band.bandKey];
    const source =
      provenance === undefined
        ? "-"
        : `${provenance.clubId} (rank ${provenance.divisionRank}/${provenance.divisionSize})`;
    return `| \`${band.bandKey}\` | ${band.goalkeeper} | ${band.defense} | ${band.midfield} | ${band.attack} | ${source} |`;
  });

  return [
    "## Measured Quality Bands",
    "",
    "Department scores measured from the generated first-choice eleven of a real",
    "club, through the production team-strength path. The `reference` band is the",
    "median first-division club flattened to one uniform value, so that every",
    "structural comparison has a single unambiguous quality number.",
    "",
    "These bands hold for a **single-country population**. With five countries,",
    "`first division` and `third division` stop denoting one quality scale and",
    "every band below must be re-derived rather than carried over.",
    "",
    "| Band | GK | Defense | Midfield | Attack | Measured from |",
    "| --- | --- | --- | --- | --- | --- |",
    ...rows,
  ];
}

function strengthSection(report: TacticalShapeAuditReport): readonly string[] {
  const grouped = new Map<string, string[]>();
  for (const row of report.strengthRows) {
    const keys = grouped.get(row.fingerprint) ?? [];
    keys.push(row.compositionKey);
    grouped.set(row.fingerprint, keys);
  }

  const rows = [...grouped.entries()].map(([fingerprint, keys]) => {
    const strength = report.strengthRows.find((row) => row.fingerprint === fingerprint)?.strength;
    return (
      `| ${keys.length} | ${score(strength?.goalkeeper)} | ${score(strength?.defense)} `
      + `| ${score(strength?.midfield)} | ${score(strength?.attack)} | ${score(strength?.overall)} `
      + `| ${keys.slice(0, 5).join(", ")}${keys.length > 5 ? ", ..." : ""} |`
    );
  });

  return [
    "## Department Collapse",
    "",
    `The reachable population is ${report.strengthRows.length} department compositions, which the current`,
    `engine reduces to **${report.distinctStrengthCount} distinct team strengths**. Every composition that`,
    "populates all four departments produces byte-identical strength, because",
    "`deriveTeamStrength` averages inside a department and therefore cannot see how",
    "many slots are in it. The only structural signal the engine has today is",
    "whether a department is *empty*.",
    "",
    "| Compositions | GK | Defense | Midfield | Attack | Overall | Members |",
    "| --- | --- | --- | --- | --- | --- | --- |",
    ...rows,
    "",
    `Compositions reachable from one of the 23 named presets: ${report.strengthRows.filter((row) => row.reachableFromPreset).length}.`,
    "The rest are reachable only by moving players on the tactical board, which no",
    "validator prevents.",
  ];
}

function equivalenceSection(report: TacticalShapeAuditReport): readonly string[] {
  const rows = report.equivalences.map(
    (row) =>
      `| \`${row.firstCompositionKey}\` | \`${row.secondCompositionKey}\` | ${yesNo(row.strengthIdentical)} `
      + `| ${yesNo(row.resultsIdentical)} | ${row.matches} |`,
  );

  return [
    "## Shape Equivalence",
    "",
    "Both compositions run on the same seeds and the same fixture identities, so a",
    "difference in results can only come from the shape.",
    "",
    "| Shape | Shape | Identical strength | Identical results | Matches |",
    "| --- | --- | --- | --- | --- |",
    ...rows,
  ];
}

function versusReferenceSection(report: TacticalShapeAuditReport): readonly string[] {
  const ordered = [...report.versusReference].sort((left, right) => right.winShare - left.winShare);
  const rows = ordered.map(
    (row) =>
      `| \`${row.compositionKey}\` | ${row.winShare} | ${row.possessionShare} | ${row.clampedTo} `
      + `| ${row.opportunities} | ${row.expectedGoals} | ${row.goals} | ${row.matches} |`,
  );

  return [
    "## Every Shape Against The Reference Shape",
    "",
    "Each reachable composition against a coherent `4-4-2` at equal quality. This is",
    "the manager's real decision, so it is measured at the higher scenario",
    "precision and is what the bounded-swing and asymmetry invariants read.",
    "",
    "| Shape | Win share | Possession | Clamp | Opportunities | xG | Goals | Matches |",
    "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ...rows,
  ];
}

function tacticSection(report: TacticalShapeAuditReport): readonly string[] {
  const rows = report.tacticProfiles.map((row) => {
    const types = row.chanceTypes;
    return (
      `| \`${row.tacticKey}\` | ${row.winShare} | ${row.possessionShare} | ${row.opportunities} `
      + `| ${row.expectedGoals} | ${types.open_play} | ${types.counter} | ${types.cross} `
      + `| ${types.dead_ball} | ${row.matches} |`
    );
  });

  return [
    "## Tactic Profiles At The Reference Shape",
    "",
    "Each profile moves one knob to its extreme against the same shape playing the",
    "neutral tactic, so whatever moves belongs to that knob. `neutral` plays itself",
    "and its win share is the measurement's own noise reading.",
    "",
    "Chance types come from a deterministic texture rather than from a route today.",
    "They are recorded as the thing Step 06 replaces, not as evidence that routes",
    "already exist.",
    "",
    "| Tactic | Win share | Possession | Opportunities | xG | Open play | Counter | Cross | Dead ball | Matches |",
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ...rows,
  ];
}

function qualitySection(report: TacticalShapeAuditReport): readonly string[] {
  const rows = report.qualityVersusStructure.map((row) => {
    const series = row.series;
    return (
      `| \`${row.scenarioKey}\` | \`${row.first.compositionKey}\` / \`${row.first.bandKey}\` `
      + `| \`${row.second.compositionKey}\` / \`${row.second.bandKey}\` | ${series.firstWinShare} `
      + `| ${series.firstWins}/${series.draws}/${series.secondWins} | ${series.first.expectedGoals} `
      + `| ${series.second.expectedGoals} | ${series.matches} |`
    );
  });

  return [
    "## Quality Versus Structure",
    "",
    "`division_tier_edge` is the yardstick: what one division tier of squad quality",
    "is worth in win share at identical shape. The bounded-swing invariant compares",
    "the best structural gain against it.",
    "",
    "| Scenario | First | Second | First win share | W/D/L | First xG | Second xG | Matches |",
    "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ...rows,
  ];
}

function invariantSection(report: TacticalShapeAuditReport): readonly string[] {
  const rows = report.invariants.map(
    (invariant) =>
      `| \`${invariant.key}\` | ${statusLabel(invariant)} | ${invariant.observed ?? "-"} `
      + `| ${invariant.observations} | ${invariant.threshold} |`,
  );

  return [
    "## Frozen Invariants",
    "",
    "Thresholds were fixed before any behaviour change and are never re-derived",
    "from output. `not_evaluated` is never reported as a pass.",
    "",
    "| Invariant | Status | Observed | Observations | Frozen threshold |",
    "| --- | --- | --- | --- | --- |",
    ...rows,
    "",
    ...report.invariants.flatMap((invariant) => [`- \`${invariant.key}\`: ${invariant.detail}`]),
  ];
}

function dominanceSection(report: TacticalShapeAuditReport): readonly string[] {
  const keys = report.dominance.compositionKeys;
  const header = ["shape", ...keys].join("\t");
  const grid = report.dominance.winShare.map((row, index) =>
    [keys[index] ?? "?", ...row.map((value) => value.toFixed(3))].join("\t"),
  );
  const aggregate = report.dominance.rows.map(
    (row) => `| \`${row.compositionKey}\` | ${row.meanWinShare} | ${row.minimumWinShare} | ${row.matches} |`,
  );

  return [
    "## Dominance Matrix",
    "",
    `The full ${keys.length} x ${keys.length} paired-seed matrix over the reachable population. Row versus`,
    "column, read as the row's win share. Recorded in full rather than summarised,",
    "because dominance shows as a row and a summary hides it.",
    "",
    "| Shape | Mean vs field | Worst matchup | Matches |",
    "| --- | --- | --- | --- |",
    ...aggregate,
    "",
    "```tsv",
    header,
    ...grid,
    "```",
  ];
}

function statusLabel(invariant: TacticalShapeInvariantResult): string {
  switch (invariant.status) {
    case "pass":
      return "PASS";
    case "fail":
      return "FAIL";
    case "not_evaluated":
      return "not_evaluated";
  }
}

function countFailedInvariants(report: TacticalShapeAuditReport): number {
  return report.invariants.filter((invariant) => invariant.status === "fail").length;
}

function yesNo(value: boolean): string {
  return value ? "yes" : "no";
}

/**
 * Renders one department score for the report.
 *
 * Presentation rounds; the fingerprint that decides equivalence does not, so a
 * difference hidden by rounding here still shows as a distinct strength row.
 */
function score(value: number | undefined): string {
  return value === undefined ? "-" : value.toFixed(4);
}

interface ParsedArgsOk {
  readonly ok: true;
  readonly worldSeed: string;
  readonly seedPrefix: string;
  readonly pairedSeedCount: number;
  readonly scenarioPairedSeedCount: number;
  readonly reportOutput: string | undefined;
}

interface ParsedArgsInvalid {
  readonly ok: false;
  readonly message: string;
}

function parseArgs(args: readonly string[]): ParsedArgsInvalid | ParsedArgsOk {
  const text = createTranslator("en");
  let worldSeed = DEFAULT_TACTICAL_SHAPE_WORLD_SEED;
  let seedPrefix = DEFAULT_TACTICAL_SHAPE_SEED_PREFIX;
  let pairedSeedCount = DEFAULT_TACTICAL_SHAPE_PAIRED_SEEDS;
  let scenarioPairedSeedCount = DEFAULT_TACTICAL_SHAPE_SCENARIO_PAIRED_SEEDS;
  let reportOutput: string | undefined;

  for (const arg of args) {
    if (arg.startsWith("--world-seed=")) {
      worldSeed = arg.slice("--world-seed=".length);
      if (worldSeed.length === 0) {
        return { ok: false, message: text("tacticalShape.error.worldSeedRequired") };
      }
      continue;
    }

    if (arg.startsWith("--seed-prefix=")) {
      seedPrefix = arg.slice("--seed-prefix=".length);
      if (seedPrefix.length === 0) {
        return { ok: false, message: text("tenSeason.error.seedPrefixRequired") };
      }
      continue;
    }

    if (arg.startsWith("--paired-seeds=")) {
      const value = arg.slice("--paired-seeds=".length);
      pairedSeedCount = Number(value);
      if (!Number.isSafeInteger(pairedSeedCount) || pairedSeedCount <= 0) {
        return { ok: false, message: text("tacticalShape.error.pairedSeedsInvalid", { value }) };
      }
      continue;
    }

    if (arg.startsWith("--scenario-paired-seeds=")) {
      const value = arg.slice("--scenario-paired-seeds=".length);
      scenarioPairedSeedCount = Number(value);
      if (!Number.isSafeInteger(scenarioPairedSeedCount) || scenarioPairedSeedCount <= 0) {
        return { ok: false, message: text("tacticalShape.error.pairedSeedsInvalid", { value }) };
      }
      continue;
    }

    if (arg.startsWith("--report-output=")) {
      reportOutput = arg.slice("--report-output=".length);
      if (reportOutput.length === 0) {
        return { ok: false, message: text("tacticalShape.error.reportOutputRequired") };
      }
      continue;
    }

    return { ok: false, message: text("cli.error.unknownArgument", { arg }) };
  }

  return { ok: true, worldSeed, seedPrefix, pairedSeedCount, scenarioPairedSeedCount, reportOutput };
}

function defaultDependencies(): TacticalShapeReportCommandDependencies {
  return {
    stdout: (line) => console.log(line),
    stderr: (line) => console.error(line),
    writeReport: async (path, contents) => {
      await mkdir(dirname(path), { recursive: true });
      await writeFile(path, contents, "utf8");
    },
    createReport: createTacticalShapeReport,
  };
}
