import { NAME_CULTURE_KEYS, type NameCultureKey } from "@game/domain";

/** Names available for one fictional name culture. */
export interface NameCulturePool {
  /** Stable culture key used by content generators. */
  readonly key: NameCultureKey;
  /** Fictional first-name entries for generated people. */
  readonly firstNames: readonly string[];
  /** Fictional last-name entries for generated people. */
  readonly lastNames: readonly string[];
}

/** Explicit deterministic order for name-culture pool review and tests. */
export const NAME_CULTURE_POOL_KEYS: readonly NameCultureKey[] = NAME_CULTURE_KEYS;

/** Content-owned fictional name pools, intentionally separate from i18n labels. */
export const NAME_CULTURE_POOLS: Readonly<Record<NameCultureKey, NameCulturePool>> = {
  italian: nameCulturePool("italian", ["Luca", "Matteo", "Davide", "Giorgio", "Nico", "Enrico"], [
    "Abate",
    "Agostini",
    "Albanesi",
    "Amato",
    "Andreoli",
    "Antonelli",
    "Baldi",
    "Barbieri",
    "Barone",
    "Bartoli",
    "Basile",
    "Bellini",
    "Benedetti",
    "Bernardi",
    "Bianchi",
    "Bini",
    "Biondi",
    "Bocchi",
    "Bonetti",
    "Borghetti",
    "Bortolotti",
    "Brambilla",
    "Bruni",
    "Bruno",
    "Caldara",
    "Calvi",
    "Capelli",
    "Capone",
    "Carbone",
    "Carli",
    "Caruso",
    "Casadei",
    "Casali",
    "Cattaneo",
    "Cavalli",
    "Cecchi",
    "Colombo",
    "Conti",
    "Coppola",
    "Costa",
    "Costantini",
    "D'Angelo",
    "Damiani",
    "De Luca",
    "De Santis",
    "Donati",
    "Esposito",
    "Fabbri",
    "Farina",
    "Ferri",
    "Ferrini",
    "Ferrari",
    "Fontana",
    "Fumagalli",
    "Galli",
    "Gallo",
    "Gatti",
    "Gentile",
    "Giordano",
    "Giuliani",
    "Grassi",
    "Greco",
    "Guidi",
    "Leoni",
    "Lombardi",
    "Longo",
    "Mancini",
    "Marchetti",
    "Mariani",
    "Marino",
    "Martini",
    "Martinelli",
    "Mazza",
    "Mazzi",
    "Melis",
    "Messina",
    "Montanari",
    "Morelli",
    "Moretti",
    "Moro",
    "Neri",
    "Orlando",
    "Palmieri",
    "Parisi",
    "Pellegrini",
    "Pellegrino",
    "Pini",
    "Rinaldi",
    "Ricci",
    "Ricciardi",
    "Rizzo",
    "Romano",
    "Rossi",
    "Rossetti",
    "Russo",
    "Sala",
    "Santoro",
    "Sartori",
    "Serra",
    "Silvestri",
    "Sorrentino",
    "Testa",
    "Valentini",
    "Villa",
    "Vitale",
    "Zanetti",
    "Zini",
    "Accardi",
    "Alberti",
    "Amoroso",
    "Angelini",
    "Baldini",
    "Bellandi",
    "Bertini",
    "Bianco",
    "Bonacina",
    "Borghese",
    "Cambi",
    "Canini",
    "Caputo",
    "Cardini",
    "Carlini",
    "Carminati",
    "Castelli",
    "Cavallini",
    "Cerri",
    "Corsi",
    "D'Amico",
    "Dal Canto",
    "De Angelis",
    "De Rosa",
    "Fabiani",
    "Falcone",
    "Fiore",
    "Fiorini",
    "Franchi",
    "Franzoni",
    "Gandolfi",
    "Garofalo",
    "Gori",
    "Grimaldi",
    "Landi",
    "Lazzari",
    "Lippi",
    "Lombardo",
    "Lorenzini",
    "Lucchesi",
    "Mancuso",
    "Mantovani",
    "Marchi",
    "Martino",
    "Masi",
    "Melandri",
    "Merlo",
    "Monti",
    "Naldi",
    "Nardini",
    "Negri",
    "Pagani",
    "Pagano",
    "Palumbo",
    "Pastore",
    "Pavan",
    "Pavoni",
    "Perini",
    "Piazza",
    "Piccoli",
    "Piras",
    "Raimondi",
    "Riva",
    "Rosati",
    "Ruggieri",
    "Sanna",
    "Santi",
    "Sassi",
    "Serafini",
    "Sordi",
    "Spinelli",
    "Taddei",
    "Tosi",
    "Trevisan",
    "Valeri",
    "Venturi",
    "Verdi",
    "Vitali",
    "Zambelli",
    "Zanchi",
    "Zappa",
    "Zorzi",
    "Acerbi",
    "Adami",
    "Ambrosi",
    "Anselmi",
    "Arena",
    "Bagnoli",
    "Balzano",
    "Basiletti",
    "Battaglia",
    "Bevilacqua",
    "Bonanni",
    "Bosco",
    "Cali",
    "Cantini",
    "Capra",
    "Carnevali",
    "Cavallaro",
    "Ceccarelli",
    "Conte",
    "Cremonesi",
    "Dalla Costa",
    "De Marchi",
    "Di Biase",
    "Di Matteo",
    "Falco",
    "Fiorentini",
    "Foschi",
    "Gagliardi",
    "Germani",
    "Guerra",
    "Lombardini",
    "Magnani",
    "Maresca",
    "Molinari",
    "Morandi",
    "Palladino",
    "Pellecchia",
    "Pierini",
    "Pugliese",
    "Righetti",
    "Rossiello",
    "Salvatori",
    "Savini",
    "Schiavone",
    "Tarantino",
    "Vallini",
    "Vannucci",
    "Zaccaria",
  ]),
  english: nameCulturePool("english", ["Oliver", "Ethan", "Callum", "Harry", "Mason", "Noah"], [
    "Bennett",
    "Carter",
    "Hughes",
    "Fletcher",
    "Turner",
    "Walsh",
  ]),
  spanish: nameCulturePool("spanish", ["Diego", "Iker", "Javier", "Raul", "Sergio", "Marcos"], [
    "Serrano",
    "Navarro",
    "Campos",
    "Molina",
    "Herrera",
    "Delgado",
  ]),
  german: nameCulturePool("german", ["Lukas", "Jonas", "Felix", "Timo", "Marvin", "Niklas"], [
    "Keller",
    "Bergmann",
    "Schuster",
    "Vogel",
    "Hartmann",
    "Weber",
  ]),
  french: nameCulturePool("french", ["Lucas", "Hugo", "Mathis", "Theo", "Nolan", "Adrien"], [
    "Moreau",
    "Lefevre",
    "Garnier",
    "Rousseau",
    "Mercier",
    "Dumont",
  ]),
  portuguese: nameCulturePool("portuguese", ["Tiago", "Ruben", "Andre", "Joao", "Miguel", "Nuno"], [
    "Ferreira",
    "Moreira",
    "Cardoso",
    "Pereira",
    "Barros",
    "Matos",
  ]),
  brazilian: nameCulturePool("brazilian", ["Caio", "Rafael", "Bruno", "Mateus", "Renan", "Vitor"], [
    "Santos",
    "Almeida",
    "Moraes",
    "Teixeira",
    "Barbosa",
    "Rezende",
  ]),
  spanish_american: nameCulturePool("spanish_american", ["Mateo", "Tomas", "Nicolas", "Emilio", "Facundo", "Lautaro"], [
    "Acosta",
    "Rojas",
    "Vargas",
    "Mendoza",
    "Paredes",
    "Sosa",
  ]),
  dutch: nameCulturePool("dutch", ["Daan", "Sem", "Milan", "Joris", "Luuk", "Bram"], [
    "Van Dalen",
    "De Wit",
    "Bakker",
    "Meijer",
    "Visser",
    "Jansen",
  ]),
  balkan: nameCulturePool("balkan", ["Luka", "Milan", "Nikola", "Marko", "Ivan", "Dario"], [
    "Petrovic",
    "Kovacic",
    "Markovic",
    "Jovanovic",
    "Stanic",
    "Radic",
    "Babic",
    "Bogdanovic",
    "Bozic",
    "Cvetkovic",
    "Djuric",
    "Horvat",
    "Ilic",
    "Knezevic",
    "Kostic",
    "Kovac",
    "Lukic",
    "Maric",
    "Milic",
    "Milosevic",
    "Nikolic",
    "Novak",
    "Pavlovic",
    "Popovic",
    "Simic",
    "Tadic",
    "Tomic",
    "Vasic",
    "Vukovic",
    "Zoric",
  ]),
  central_eastern_european: nameCulturePool(
    "central_eastern_european",
    ["Jakub", "Marek", "Tomasz", "Adam", "Kamil", "Pavel"],
    ["Nowak", "Kowalski", "Zielinski", "Kral", "Horak", "Malik"],
  ),
  west_african: nameCulturePool("west_african", ["Moussa", "Ibrahima", "Amadou", "Sekou", "Yaya", "Oumar"], [
    "Diop",
    "Traore",
    "Sarr",
    "Camara",
    "Keita",
    "Diallo",
  ]),
  north_african: nameCulturePool("north_african", ["Youssef", "Karim", "Nabil", "Samir", "Adil", "Rayan"], [
    "Benali",
    "Haddad",
    "Mansouri",
    "Amrani",
    "El Idrissi",
    "Ziani",
  ]),
  turkish: nameCulturePool("turkish", ["Emir", "Arda", "Kerem", "Mert", "Can", "Yusuf"], [
    "Yilmaz",
    "Demir",
    "Kaya",
    "Celik",
    "Aydin",
    "Sahin",
  ]),
  american: nameCulturePool("american", ["Logan", "Tyler", "Austin", "Cameron", "Dylan", "Ryan"], [
    "Parker",
    "Brooks",
    "Reed",
    "Morgan",
    "Coleman",
    "Hayes",
  ]),
  japanese: nameCulturePool("japanese", ["Haruto", "Ren", "Sota", "Yuto", "Kaito", "Daichi"], [
    "Mori",
    "Ishikawa",
    "Nakano",
    "Fujita",
    "Kobayashi",
    "Tanaka",
  ]),
  korean: nameCulturePool("korean", ["Minjun", "Jiho", "Seojun", "Hyunwoo", "Jisung", "Taeyang"], [
    "Kim",
    "Lee",
    "Park",
    "Choi",
    "Jung",
    "Kang",
  ]),
};

/**
 * Retrieves the content-owned name pool for one culture key.
 */
export function getNameCulturePool(key: NameCultureKey): NameCulturePool {
  return NAME_CULTURE_POOLS[key];
}

function nameCulturePool(
  key: NameCultureKey,
  firstNames: readonly string[],
  lastNames: readonly string[],
): NameCulturePool {
  return {
    key,
    firstNames,
    lastNames,
  };
}
