import {
  type Club,
  type Player,
  type PlayerDynamicState,
  type PlayerId,
} from "@game/domain";

/** One player prepared for career-world intake. */
export interface CareerIntakeCandidate {
  /** Generated player entity. */
  readonly player: Player;
  /** Initial dynamic state for the generated player. */
  readonly playerState: PlayerDynamicState;
  /** Intended receiving club for later squad-refresh application. */
  readonly targetClubId: Club["id"];
}

/** Structured intake record for reports and later refresh steps. */
export interface CareerIntakeRecord {
  /** Player generated by the intake pool. */
  readonly playerId: PlayerId;
  /** Intended receiving club. */
  readonly targetClubId: Club["id"];
  /** Natural position used by later squad-shape maintenance. */
  readonly primaryPosition: NonNullable<Player["naturalPositions"][number]>;
}

/** Machine-readable intake-pool validation failure. */
export type CareerIntakePoolErrorCode =
  | "duplicate_intake_player"
  | "player_already_active"
  | "target_club_not_found"
  | "missing_primary_position";

/** Error thrown when a generated intake pool is not safe to consume. */
export class CareerIntakePoolError extends Error {
  /** Stable machine-readable validation code. */
  public readonly code: CareerIntakePoolErrorCode;

  /** Creates an intake-pool validation error. */
  public constructor(code: CareerIntakePoolErrorCode, message: string) {
    super(message);
    this.name = "CareerIntakePoolError";
    this.code = code;
  }
}

/** Input for validating a generated intake pool against the current career state. */
export interface CreateCareerIntakePoolInput {
  /** Current active player IDs, kept explicit to avoid object-order inference. */
  readonly activePlayerIds: readonly PlayerId[];
  /** Current active club IDs. */
  readonly activeClubIds: readonly Club["id"][];
  /** Generated intake candidates in deterministic order. */
  readonly candidates: readonly CareerIntakeCandidate[];
}

/** Result of validating a generated intake pool. */
export interface CreateCareerIntakePoolResult {
  /** Safe candidates in deterministic order. */
  readonly candidates: readonly CareerIntakeCandidate[];
  /** Report records for later metrics. */
  readonly records: readonly CareerIntakeRecord[];
}

/**
 * Validates a generated career intake pool without applying it to rosters.
 *
 * Step 03 owns pool creation and validation only. Later squad-maintenance code
 * decides which candidates a club actually receives.
 */
export function createCareerIntakePool(input: CreateCareerIntakePoolInput): CreateCareerIntakePoolResult {
  const activePlayerIds = new Set(input.activePlayerIds);
  const activeClubIds = new Set(input.activeClubIds);
  const seenIntakePlayerIds = new Set<PlayerId>();
  const records: CareerIntakeRecord[] = [];

  for (const candidate of input.candidates) {
    if (seenIntakePlayerIds.has(candidate.player.id)) {
      throw new CareerIntakePoolError("duplicate_intake_player", `duplicate intake player: ${candidate.player.id}`);
    }

    if (activePlayerIds.has(candidate.player.id)) {
      throw new CareerIntakePoolError("player_already_active", `intake player already active: ${candidate.player.id}`);
    }

    if (!activeClubIds.has(candidate.targetClubId)) {
      throw new CareerIntakePoolError("target_club_not_found", `target club does not exist: ${candidate.targetClubId}`);
    }

    const primaryPosition = candidate.player.naturalPositions[0];
    if (primaryPosition === undefined) {
      throw new CareerIntakePoolError("missing_primary_position", `intake player has no natural position: ${candidate.player.id}`);
    }

    seenIntakePlayerIds.add(candidate.player.id);
    records.push({
      playerId: candidate.player.id,
      targetClubId: candidate.targetClubId,
      primaryPosition,
    });
  }

  return {
    candidates: input.candidates,
    records,
  };
}
