/** Public entrypoint for deterministic AI team-selection helpers. */
export {
  applyAiInGameDecision,
  applyProgressiveAiInGameDecisions,
  hasProgressiveAiInGameDecisionBoundary,
  runAutomatedProgressiveMatch,
  selectAiInGameDecision,
  type AiInGameDecisionReason,
  type AiInGameDecisionReasonKey,
  type AiInGameReplacementFailureKey,
  type AiInGameDecisionSelection,
  type AiInGameFormationOption,
  type AiInGamePlayerSignal,
  type ApplyAiInGameDecisionResult,
  type ApplyProgressiveAiInGameDecisionsInput,
  type ApplyProgressiveAiInGameDecisionsResult,
  type AutomatedProgressiveAiDecision,
  type ProgressiveAiInGameDecision,
  type RunAutomatedProgressiveMatchInput,
  type RunAutomatedProgressiveMatchResult,
  type SelectAiInGameDecisionInput,
} from "./ai-in-game-decisions.ts";
export { deriveShapeTacticalDistribution } from "./shape-tactical-distribution.ts";
export {
  AiSquadSelectionError,
  buildAiSquadMatchTeamContext,
  selectAiMatchSquad,
  type AiRecentPlayerUse,
  type AiSquadSelectionErrorCode,
  type AiSquadSelectionInput,
  type AiSquadSelectionReason,
  type AiSquadSelectionResult,
  type BuildAiSquadMatchTeamContextInput,
  type BuildAiSquadMatchTeamContextResult,
  type CatalogShapeChoice,
} from "./ai-squad-selection.ts";
