/**
 * Public entrypoint for deterministic offline simulation tooling.
 *
 * Simulation tools may depend on `domain`, `engine`, and `shared`, but must not
 * import content, storage, or apps. App shells provide content-specific input.
 */
export {
  createCalibrationReport,
  seasonSeed,
  type CalibrationMetricKey,
  type CalibrationMetricResult,
  type CalibrationReport,
  type CalibrationSeasonSummary,
  type CalibrationTarget,
  type CreateCalibrationReportInput,
} from "./calibration-report.ts";

export {
  SIMULATION_REPORT_CONTRACT_VERSION,
  canonicalSimulationReportJson,
  createSimulationReportArtifact,
  parseSimulationReportArtifact,
  stableSimulationReportHash,
  toSimulationReportJsonValue,
  type CreateSimulationReportArtifactInput,
  type SimulationReportArtifact,
  type SimulationReportDetail,
  type SimulationReportExecutionNode,
  type SimulationReportJsonValue,
  type SimulationReportManifest,
  type SimulationReportMeasurementRequest,
  type SimulationReportSection,
  type SimulationReportSectionStatus,
} from "./modular-report/report-contract.ts";

export {
  createPlayerMarketCalibrationReport,
  type CreatePlayerMarketCalibrationReportInput,
  type PlayerMarketCalibrationObservation,
  type PlayerMarketCalibrationPopulation,
  type PlayerMarketCalibrationReport,
  type PlayerMarketCalibrationSampleMetadata,
  type PlayerMarketClubSquadObservation,
  type PlayerMarketDivisionDiagnostic,
  type PlayerMarketDivisionValueFit,
  type PlayerMarketSquadComparator,
  type PlayerMarketValueFitCheck,
  type PlayerRatingHistogram,
} from "./player-market-calibration-report.ts";

export {
  createPlayerDevelopmentCohortWorldSummary,
  mergePlayerDevelopmentCohortAggregates,
  mergePlayerDevelopmentCohortWorldSummaries,
  validatePlayerDevelopmentCohortAggregateSummary,
  validatePlayerDevelopmentCohortWorldSummary,
  PLAYER_DEVELOPMENT_ABILITY_GAP_BUCKETS,
  PLAYER_DEVELOPMENT_AGE_BANDS,
  PLAYER_DEVELOPMENT_COHORT_CONTRACT_VERSION,
  PLAYER_DEVELOPMENT_COHORT_GATE_KEYS,
  PLAYER_DEVELOPMENT_ENVIRONMENT_EFFECTS,
  PLAYER_DEVELOPMENT_MONEY_BUCKETS,
  PLAYER_DEVELOPMENT_MONEY_BUCKET_UPPER_BOUNDS_MINOR_UNITS,
  PLAYER_DEVELOPMENT_OPPORTUNITY_BANDS,
  PLAYER_DEVELOPMENT_PERFORMANCE_BANDS,
  PLAYER_DEVELOPMENT_POPULATIONS,
  PLAYER_DEVELOPMENT_ROOM_REALIZATION_BUCKETS,
  PLAYER_DEVELOPMENT_STAR_DELTAS,
  type CreatePlayerDevelopmentCohortWorldSummaryInput,
  type PlayerDevelopmentAbilityGapBucket,
  type PlayerDevelopmentAgeBand,
  type PlayerDevelopmentCheckpointAgeBandSummary,
  type PlayerDevelopmentCheckpointObservation,
  type PlayerDevelopmentCheckpointSummary,
  type PlayerDevelopmentCohortAggregateSummary,
  type PlayerDevelopmentCohortGate,
  type PlayerDevelopmentCohortWorldSummary,
  type PlayerDevelopmentEnvironmentEffect,
  type PlayerDevelopmentExactGapSummary,
  type PlayerDevelopmentGrowthCell,
  type PlayerDevelopmentMoneyBucket,
  type PlayerDevelopmentNewEntrantSummary,
  type PlayerDevelopmentNumericSummary,
  type PlayerDevelopmentOpportunityBand,
  type PlayerDevelopmentParticipationObservation,
  type PlayerDevelopmentPerformanceBand,
  type PlayerDevelopmentPlateauSummary,
  type PlayerDevelopmentPopulationCounts,
  type PlayerDevelopmentProjectionFacts,
  type PlayerDevelopmentRatingHistogram,
  type PlayerDevelopmentRoomRealizationBucket,
  type PlayerDevelopmentStarDelta,
  type PlayerDevelopmentStarDeltaHistogram,
  type PlayerDevelopmentStructuralViolationExample,
  type PlayerDevelopmentTrajectoryAgeBandSummary,
  type PlayerDevelopmentYoungCeilingSixValueSlice,
} from "./player-development-cohort-audit.ts";

export {
  createPlayerGenerationEconomyAudit,
  createPlayerGenerationAnnualIntakeSummary,
  type CreatePlayerGenerationEconomyAuditInput,
  type PlayerGenerationAnnualIntakeObservation,
  type PlayerGenerationAnnualIntakeSummary,
  type PlayerExceptionalAllocationLabels,
  type PlayerGenerationAiDecisionKind,
  type PlayerGenerationAiInformationParityObservation,
  type PlayerGenerationAiInformationParitySummary,
  type PlayerGenerationAllocationSummary,
  type PlayerGenerationCapSummary,
  type PlayerGenerationCurrentRatingGuardrail,
  type PlayerGenerationFreeAgentSigningObservation,
  type PlayerGenerationFreeAgentSigningSummary,
  type PlayerGenerationEconomyAudit,
  type PlayerGenerationEconomyGate,
  type PlayerGenerationEconomyObservation,
  type PlayerGenerationExceptionalSlice,
  type PlayerGenerationExceptionalStockClubAssociation,
  type PlayerGenerationExceptionalStockPlayerObservation,
  type PlayerGenerationExceptionalStockSnapshotObservation,
  type PlayerGenerationExceptionalStockSnapshotSummary,
  type PlayerGenerationExceptionalStockSummary,
  type PlayerGenerationExceptionalStockTransitionSummary,
  type PlayerGenerationGateExample,
  type PlayerGenerationGateStatus,
  type PlayerGenerationInitialRarityConstraints,
  type PlayerGenerationIntrinsicValueInvarianceObservation,
  type PlayerGenerationIntrinsicValueInvarianceSummary,
  type PlayerGenerationMoneyDistribution,
  type PlayerGenerationNegotiationObservation,
  type PlayerGenerationNegotiationSummary,
  type PlayerGenerationCounterOutcome,
  type PlayerGenerationNumberDistribution,
  type PlayerGenerationPopulation,
  type PlayerGenerationPotentialRangeSlice,
  type PlayerGenerationRatioDistribution,
  type PlayerGenerationRatingDistribution,
  type PlayerGenerationRoleGroup,
  type PlayerGenerationSellerOutcome,
  type PlayerGenerationSquadPlacement,
  type PlayerGenerationValueTransition,
  type SuppliedNegotiationAggregate,
} from "./player-generation-economy-audit.ts";

export {
  createPotentialProjectionPolicyCalibration,
  createPlayerPotentialOutcomeAudit,
  type CreatePlayerPotentialOutcomeAuditInput,
  type PlayerPotentialOutcomeAudit,
  type PlayerPotentialOutcomeCell,
  type PlayerPotentialOutcomeCoverageContract,
  type PlayerPotentialOutcomeGate,
  type PlayerPotentialOutcomeGateExample,
  type PlayerPotentialOutcomeObservation,
  type PotentialProjectionCalibrationAgeBand,
  type PotentialProjectionPolicyCalibrationBand,
  type PotentialOutcomeDistribution,
  type PotentialOutcomeParticipationBand,
  type PotentialOutcomeRoleGroup,
  type PotentialOutcomeRoomBand,
} from "./player-potential-outcome-audit.ts";

export {
  DEFAULT_LONG_RUN_SEASON_COUNT,
  longRunSeasonSeed,
  runLongRunSimulation,
  type CreateLongRunSeasonInputContext,
  type LongRunSeasonResult,
  type LongRunSimulationResult,
  type RunLongRunSimulationInput,
} from "./long-run/long-runner.ts";

export {
  SIMULATION_WORKER_LIMIT,
  resolveSimulationWorkerCount,
  type ResolveSimulationWorkerCountInput,
} from "./simulation-execution-policy.ts";

export {
  runCareerLongRunSimulation,
  type AdvanceCareerLongRunSeasonContext,
  type AdvanceCareerLongRunSeasonResult,
  type CareerLongRunAdvancedSeasonObservation,
  type CareerLongRunRefreshSummary,
  type CareerLongRunSeasonResult,
  type CareerLongRunSimulationResult,
  type CreateCareerLongRunSeasonInputContext,
  type RunCareerLongRunSimulationInput,
} from "./long-run/career-long-runner.ts";

export {
  createLongRunPlayerEvolutionReport,
  type CreateLongRunPlayerEvolutionReportInput,
  type LongRunPlayerEvolutionReport,
  type LongRunPlayerMovementRow,
  type LongRunPlayerProductionRow,
  type LongRunPlayerSnapshotRow,
  type LongRunPlayerTrajectoryCheck,
  type LongRunPlayerTrajectoryDiagnostics,
  type LongRunPlayerTrajectorySampleRow,
} from "./long-run/player-evolution.ts";

export {
  createLongRunClubStabilityReport,
  type LongRunClubSeasonRow,
  type LongRunClubStabilityReport,
  type LongRunRefreshTotals,
} from "./long-run/club-stability.ts";

export {
  createLongRunAnomalyReport,
  LONG_RUN_ANOMALY_KEYS,
  longRunAnomalySemanticClass,
  projectLongRunAnomalyCheckForWorldGate,
  worstLongRunAnomalyStatus,
  type CreateLongRunAnomalyReportInput,
  type LongRunAnomalyCheck,
  type LongRunAnomalyKey,
  type LongRunAnomalyReport,
  type LongRunAnomalySemanticClass,
  type LongRunAnomalyStatus,
  type LongRunBalanceSeasonRow,
  type ProjectedLongRunAnomalyCheck,
} from "./long-run/anomaly-scoring.ts";

export {
  createLongRunYouthStabilityReport,
  type CreateLongRunYouthStabilityReportOptions,
  type LongRunYouthSeasonRow,
  type LongRunYouthStabilityCheck,
  type LongRunYouthStabilityReport,
} from "./long-run/youth-stability.ts";

export {
  createLongRunContractFinanceSeasonRow,
  createLongRunContractFinanceStabilityReport,
  type CreateLongRunContractFinanceSeasonRowInput,
  type LongRunContractFinanceCheck,
  type LongRunContractFinanceSeasonRow,
  type LongRunContractFinanceStabilityReport,
  type LongRunCrossTierTransferRow,
  type LongRunDivisionMarketEconomyRow,
  type LongRunDivisionWageEconomyRow,
  type LongRunFreeAgentBands,
  type LongRunFreeAgentFlow,
  type LongRunLedgerReasonAmounts,
  type LongRunPermanentTransferFunnel,
  type LongRunPreliminaryAgreementFunnel,
  type LongRunSquadDepartment,
} from "./long-run/contract-finance-stability.ts";

export {
  buildTacticalShapeMatchContext,
  buildTacticalShapeTeamContext,
  deriveTacticalShapeStrength,
  runTacticalShapeAudit,
  runTacticalShapeSeries,
  tacticalShapeCompositionKey,
  TacticalShapeAuditError,
  TACTICAL_SHAPE_AUDIT_CONTRACT_VERSION,
  TACTICAL_SHAPE_COMPOSITIONS,
  TACTICAL_SHAPE_EXTREME_COMPOSITION_KEYS,
  TACTICAL_SHAPE_FORMATION_POPULATION,
  TACTICAL_SHAPE_LINEUP_SLOT_COUNT,
  TACTICAL_SHAPE_NEUTRAL_TACTIC,
  TACTICAL_SHAPE_OUTFIELD_SLOT_COUNT,
  TACTICAL_SHAPE_PRESET_COMPOSITION_KEYS,
  TACTICAL_SHAPE_REFERENCE_COMPOSITION_KEY,
  TACTICAL_SHAPE_THRESHOLDS,
  TACTICAL_SHAPE_TACTIC_PROFILES,
  type BuildTacticalShapeMatchContextInput,
  type RunTacticalShapeAuditInput,
  type RunTacticalShapeSeriesInput,
  type TacticalShapeAuditErrorCode,
  type TacticalShapeAuditReport,
  type TacticalShapeComposition,
  type TacticalShapeCompositionKey,
  type TacticalShapeCounterMoveRow,
  type TacticalShapeDominanceMatrix,
  type TacticalShapeDominanceRow,
  type TacticalShapeEquivalenceRow,
  type TacticalShapeFormationDominanceMatrix,
  type TacticalShapeFormationDominanceRow,
  type TacticalShapeGateStatus,
  type TacticalShapeInvariantKey,
  type TacticalShapeInvariantResult,
  type TacticalShapeQualityBand,
  type TacticalShapeQualityBands,
  type TacticalShapeQualityStructureRow,
  type TacticalShapeSeriesResult,
  type TacticalShapeSeriesSideTotals,
  type TacticalShapeSide,
  type TacticalShapeSideLabel,
  type TacticalShapeStrengthRow,
  type TacticalShapeTacticDominanceMatrix,
  type TacticalShapeTacticProfile,
  type TacticalShapeTacticRow,
  type TacticalShapeVersusReferenceRow,
} from "./tactical-shape/tactical-shape-audit.ts";

export {
  liveMatchControlWorldSeed,
  runLiveMatchControlGate,
  verifyLiveMatchControlGateReproducibility,
  type LiveMatchControlDistribution,
  type LiveMatchControlDistributionKey,
  type LiveMatchControlFailure,
  type LiveMatchControlFixtureSetup,
  type LiveMatchControlGateReport,
  type LiveMatchControlGateWorld,
  type LiveMatchControlInvariantKey,
  type LiveMatchControlReproducibility,
  type LiveMatchControlResultRates,
  type LiveMatchControlWorldSummary,
  type RunLiveMatchControlGateInput,
} from "./live-match/live-match-control-gate.ts";

export {
  buildSeasonRecap,
  isCreatorRole,
  SEASON_RECAP_CHART_SIZE,
  SEASON_RECAP_CREATOR_ROLE,
  SEASON_RECAP_ROLE_GROUP,
  SeasonRecapError,
  type BuildSeasonRecapInput,
  type SeasonRecap,
  type SeasonRecapErrorCode,
  type SeasonRecapFacts,
  type SeasonRecapPlayer,
  type SeasonRecapPlayerRow,
  type SeasonRecapRoleGroup,
  type SeasonRecapShapeRow,
  type SeasonRecapTableRow,
} from "./season-recap/season-recap.ts";

export {
  evaluateSeasonRecapGates,
  SEASON_RECAP_ANCHOR_ROLES,
  SEASON_RECAP_BANDS,
  SEASON_RECAP_CHECK_KEYS,
  type SeasonRecapBand,
  type SeasonRecapCheck,
  type SeasonRecapCheckKey,
  type SeasonRecapGateResult,
} from "./season-recap/season-recap-gates.ts";

export {
  assignFormationsByClub,
  FORMATION_ASSIGNMENT_STREAM,
  formationForClub,
  type AssignFormationsByClubInput,
} from "./season-recap/formation-assignment.ts";

export {
  buildTacticalAgencyStructuralActions,
  buildTacticalAgencyConditionedResponses,
  buildTacticalAgencyAuditReport,
  countTacticalAgencyOutOfPositionSlots,
  isValidTacticalAgencyCheckpointWorkerCount,
  legacyPhase81ControlWeightReference,
  poolTacticalAgencyLowBlockResults,
  observeTacticalAgencyTeamSelection,
  runTacticalAgencyOwnershipReplay,
  runTacticalAgencyLowBlockSeries,
  runTacticalAgencySelectionSeries,
  runTacticalAgencyStructuralAnalyticPartition,
  runTacticalAgencyConditionedAnalyticPartition,
  runTacticalAgencyConditionedReplayPartition,
  selectTacticalAgencyConditionedReplayContexts,
  summarizeTacticalAgencyConditionedAnalysis,
  summarizeTacticalAgencyConditionedReplay,
  summarizeTacticalAgencyStructuralAnalysis,
  summarizeTacticalAgencyPrimaryRoles,
  summarizeTacticalAgencySelections,
  summarizeTacticalAgencySquadIdentities,
  tacticalAgencyReorderInvariantShare,
  TACTICAL_AGENCY_AUDIT_CONTRACT_VERSION,
  TACTICAL_AGENCY_B_ANALYTIC_CONTRACT_VERSION,
  TACTICAL_AGENCY_B2_ANALYTIC_CONTRACT_VERSION,
  TACTICAL_AGENCY_B2_MAX_REPLAY_CONTEXTS,
  TACTICAL_AGENCY_B2_REPLAY_SEEDS_PER_CONTEXT,
  TACTICAL_AGENCY_B2_SELECTION_SEEDS_PER_CANDIDATE,
  TACTICAL_AGENCY_B_MATERIAL_ARC_BASIS_POINTS,
  TACTICAL_AGENCY_B_TACTIC_KEYS,
  TACTICAL_AGENCY_CHECKPOINT_WORKER_COUNT,
  TacticalAgencyAuditError,
  type TacticalAgencyAuditErrorCode,
  type TacticalAgencyAuditReport,
  type TacticalAgencyBTacticKey,
  type TacticalAgencyConditionedAnalysis,
  type TacticalAgencyAnalyticThreatComponents,
  type TacticalAgencyConditionedCandidateRow,
  type TacticalAgencyConditionedContextRow,
  type TacticalAgencyConditionedCycle,
  type TacticalAgencyConditionedMatchupInput,
  type TacticalAgencyConditionedReplayContext,
  type TacticalAgencyConditionedReplayContextResult,
  type TacticalAgencyConditionedReplayEstimate,
  type TacticalAgencyConditionedReplayMatchupInput,
  type TacticalAgencyConditionedReplaySummary,
  type TacticalAgencyConditionedResponse,
  type TacticalAgencyExpectedGoalsRow,
  type TacticalAgencyFormationShareRow,
  type TacticalAgencyLowBlockResult,
  type TacticalAgencyLowBlockSeriesInput,
  type TacticalAgencyOwnershipReplayResult,
  type TacticalAgencyObservedSelection,
  type TacticalAgencyPopulationManifest,
  type TacticalAgencyRoleShareRow,
  type TacticalAgencyRoleSummary,
  type TacticalAgencySelectionRow,
  type TacticalAgencySelectionSeriesInput,
  type TacticalAgencySelectionSeriesResult,
  type TacticalAgencySelectionSummary,
  type TacticalAgencySelectionWorkItem,
  type TacticalAgencySquadIdentityRow,
  type TacticalAgencySquadIdentitySummary,
  type TacticalAgencyStructuralAction,
  type TacticalAgencyStructuralAnalysis,
  type TacticalAgencyStructuralCandidateRow,
  type TacticalAgencyStructuralContextRow,
  type TacticalAgencyStructuralCycle,
  type TacticalAgencyStructuralResponseCoverage,
  type TacticalAgencyStructuralStanding,
  type TacticalAgencyTacticRow,
} from "./tactical-agency/tactical-agency-audit.ts";

export {
  decideTacticalAgencyConditionedOwner,
  firstCoherentTacticalAgencyComponent,
  summarizeTacticalAgencyConditionedAttribution,
  tacticalAgencyShapeAsymmetryBasisPoints,
  TACTICAL_AGENCY_B21_ASYMMETRY_BASIS_POINTS,
  type TacticalAgencyB21BestResponseGroup,
  type TacticalAgencyB21ComponentKey,
  type TacticalAgencyB21ComponentWorldRow,
  type TacticalAgencyB21FocusTacticRow,
  type TacticalAgencyB21TacticalAttribution,
  type TacticalAgencyB21TacticalOwner,
  type TacticalAgencyB21TacticFocusRow,
  type TacticalAgencyConditionedAttributionMatchup,
} from "./tactical-agency/tactical-agency-attribution.ts";
